### ISSUE TITLE
Melakukan survey pengguna

### ISSUE THREAD

**Issue by novaldypratama** [novaldypratama/LeafLook#11]

**Comment by alfathlathif-collage** [comment]
Section 1
- Penjelasan proyek

Section 2
- Pekerjaan
- Usia
- Apakah memiliki tanaman dirumah
- Jenis tanaman yang dimiliki

Section 3
- Apakah anda pernah memiliki tanaman yang terjangkit penyakit
- Apakah anda memiliki pengetahuan mengenai penyakit tanaman
- Apakah anda memiliki kesulitan dalam mendeteksi penyakit tanaman
- Menurut anda solusi yang ditawarkan akan membantu mengidentifikasi penyakit tanaman (1-5)
- Apakah memerlukan fitur tersebut (1-5)
- Apakah anda memiliki saran untuk membantu menyelesaikan permasalahan penyakit tanaman
